name: FileOnQ.Imaging.Heif

on:
  push:
    branches: [ build ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302

#    - name: Install VC++ Redistributable (x86)
#      shell: powershell
#      run: | 
#        wget https://aka.ms/vs/16/release/vc_redist.x86.exe -o vc_redist.x86.exe
#        .\vc_redist.x86.exe
#
#    - name: Install VC++ Redistributable (x64)
#      shell: powershell
#      run: | 
#        wget https://aka.ms/vs/16/release/vc_redist.x64.exe -o vc_redist.x64.exe
#        .\vc_redist.x64.exe

    - name: Install Build Dependencies
      run: |
        choco install meson
        choco install ninja
        choco install nasm
        echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files\Meson" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Set PR Version
      run: echo "PACKAGE_VERSION=1.0.0-pr.${{ GITHUB.RUN_NUMBER }}" >> $env:GITHUB_ENV

    - name: Build
      run: dotnet build src/FileOnQ.Imaging.Heif/FileOnQ.Imaging.Heif.csproj -c Release
      
    - name: Pack
      run: dotnet pack src/FileOnQ.Imaging.Heif/FileOnQ.Imaging.Heif.csproj -c Release -o . /p:ContinuousIntegrationBuild=true /p:Version=${{ env.PACKAGE_VERSION }} /p:PackageVersion=${{ env.PACKAGE_VERSION }}
      
    - name: Upload NuGet Package
      uses: actions/upload-artifact@v2
      with:
        name: Packages
        path: |
          *.nupkg
          *.snupkg