name: FileOnQ.Imaging.Heif

on:
  push:
    branches: [ build ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install meson and ninja
      run: pip install meson ninja

    - name: Build
      run: dotnet build src/FileOnQ.Imaging.Raw/FileOnQ.Imaging.Raw.csproj