name: FileOnQ.Imaging.Heif

on:
  push:
    branches: [ build ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    outputs:
      package_version: ${{ env.PACKAGE_VERSION }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302

    - name: Install Build Dependencies
      run: |
        choco install meson
        choco install ninja
        choco install nasm
        echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files\Meson" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Set PR Version
      run: echo "PACKAGE_VERSION=1.0.0-pr.${{ GITHUB.RUN_NUMBER }}" >> $env:GITHUB_ENV

    - name: Build
      run: dotnet build src/FileOnQ.Imaging.Heif/FileOnQ.Imaging.Heif.csproj -c Release
      
    - name: Pack
      run: dotnet pack src/FileOnQ.Imaging.Heif/FileOnQ.Imaging.Heif.csproj -c Release -o . /p:ContinuousIntegrationBuild=true /p:Version=${{ env.PACKAGE_VERSION }} /p:PackageVersion=${{ env.PACKAGE_VERSION }}
      
    - name: Upload NuGet Package
      uses: actions/upload-artifact@v2
      with:
        name: Packages
        path: |
          *.nupkg
          *.snupkg

  console-app:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net48'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net48'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net48'
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net5'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net5'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net5'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: Packages
      
      - name: View Contents
        shell: powershell
        run: ls
        
      - name: Update NuGet
        run: dotnet add package FileOnQ.Imaging.Heif --version ${{ needs.build.outputs.package_version }}
        working-directory: ./samples/ConsoleApp/ConsoleApp.${{ matrix.framework }}.${{ matrix.architecture }}
        
      - name: Run Console App
        run: dotnet run -c Release
        working-directory: ./samples/ConsoleApp/ConsoleApp.${{ matrix.framework }}.${{ matrix.architecture }}